### ISSUE TITLE
summary(TPC) seems wrong

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#17]
For RaceID the colSum is always 5000, resulting in a non-informative summary.
The number itself seems to go back to the choice in render_data_head (from aux.R),
and I don't know the origin.

**Comment by katsikora** [comment]
For RaceID3, colsums are scaled to 1, resulting in fractional counts which are not useful for anything. I have hence rescaled columns to an arbitrarily large number (5000).
Since the data is normalized, the summary is flat. 
In Seurat3, this is done by the package functions and the default scaling factor is 10000, which again gives a flat summary.
Monocle2 has a different philosophy, such that size factors are computed but the data is not rescaled to fixed volume . This gives a summary that is a bit less flat.

**Comment by thomasmanke** [comment]
This comment belongs to this issue - and yes >0 is important.
===================================
Since you are counting non-zero entries

summary(colSums(as.matrix(ndata)))

should probably be

summary(colSums(as.matrix(ndata)>0))

**Comment by katsikora** [comment]
In reality, ndata>0 will produce a logical vector, and summing over that will not sum the counts, but the number of nonzero entries per column. This is very different from what I want to return. 

 I want to return a (summary of) Transcripts Per Cell, calculated as colSums of the gene expression matrix. These are not changed by including genes with zero expression.

**Comment by katsikora** [comment]
Also, I think there are multiple different choices for the user to normalize their data in each package. It doesn't always have to result in a flat summary.
